runtime: nodejs22
env: standard
instance_class: F1
automatic_scaling:
  min_instances: 0
  max_instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
network:
  session_affinity: true
handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
